// Fictional demo data. None of these listings, agents or agencies are real.

const photo = (id) => `https://images.unsplash.com/photo-${id}?w=1200&q=70&auto=format&fit=crop`;

const demoAgents = [
  {
    name: 'Aarav Mehta',
    email: 'aarav.agent@example.com',
    profile: {
      agency: 'Nestway Realty',
      phone: '+91 98200 11223',
      city: 'Pune',
      experienceYears: 9,
      bio: 'Helps families and first-time buyers find well-connected homes across Pune and Mumbai.',
      specialties: ['Apartments', 'First homes', 'Rentals'],
    },
  },
  {
    name: 'Priya Nair',
    email: 'priya.agent@example.com',
    profile: {
      agency: 'Southline Homes',
      phone: '+91 99000 44556',
      city: 'Bengaluru',
      experienceYears: 12,
      bio: 'Specialises in homes and office spaces near the tech corridors of Bengaluru and Hyderabad.',
      specialties: ['Commercial', 'Independent houses', 'Relocation'],
    },
  },
  {
    name: 'Kabir Shekhawat',
    email: 'kabir.agent@example.com',
    profile: {
      agency: 'Courtyard Estates',
      phone: '+91 94140 77889',
      city: 'Jaipur',
      experienceYears: 7,
      bio: 'Finds villas, heritage homes and holiday plots in Jaipur and Goa.',
      specialties: ['Villas', 'Heritage homes', 'Land'],
    },
  },
];

const demoBuyers = [
  { name: 'Riya Sharma', email: 'riya.buyer@example.com' },
  { name: 'Dev Patel', email: 'dev.buyer@example.com' },
];

// agentIndex points into demoAgents.
const properties = [
  {
    agentIndex: 0,
    title: 'Riverstone Residency',
    description:
      'A bright 3 BHK on the 9th floor with an open living area, a balcony facing the hills and a modular kitchen. The society has a clubhouse, pool and covered parking, and is a short drive from Baner high street.',
    propertyType: 'Apartment',
    listingType: 'sale',
    price: 13500000,
    city: 'Pune',
    state: 'Maharashtra',
    address: '14 Riverside Road, Baner',
    bedrooms: 3,
    bathrooms: 3,
    area: 1450,
    amenities: ['Swimming pool', 'Clubhouse', 'Covered parking', 'Power backup', 'Gym'],
    featured: true,
    images: [photo('1545324418-cc1a3fa10c00'), photo('1502672260266-1c1ef2d93688'), photo('1484154218962-a197022b5858')],
  },
  {
    agentIndex: 0,
    title: 'Greenfield Heights',
    description:
      'A well-kept 2 BHK close to the Hinjewadi IT park. Semi-furnished with wardrobes, a washing machine and a fridge. Ideal for working professionals or a small family.',
    propertyType: 'Apartment',
    listingType: 'rent',
    price: 28000,
    city: 'Pune',
    state: 'Maharashtra',
    address: 'B-602, Phase 1, Hinjewadi',
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    amenities: ['Semi-furnished', 'Lift', 'Security', 'Children play area'],
    featured: false,
    images: [photo('1522708323590-d24dbb6b0267'), photo('1505691938895-1758d7feb511')],
  },
  {
    agentIndex: 0,
    title: 'Skyline Studio',
    description:
      'A compact, fully furnished studio with floor-to-ceiling windows and city views. Walking distance from Lower Parel station and the business district.',
    propertyType: 'Studio',
    listingType: 'rent',
    price: 42000,
    city: 'Mumbai',
    state: 'Maharashtra',
    address: '22nd floor, Mill Compound Towers, Lower Parel',
    bedrooms: 1,
    bathrooms: 1,
    area: 420,
    amenities: ['Fully furnished', 'Gym', 'Concierge', 'High-speed internet'],
    featured: true,
    images: [photo('1560448204-e02f11c3d0e2'), photo('1493809842364-78817add7ffb')],
  },
  {
    agentIndex: 0,
    title: 'Seabreeze Apartments',
    description:
      'A sea-facing 2 BHK a few minutes from Carter Road promenade. Recently renovated bathrooms, Italian marble flooring and a dedicated parking spot.',
    propertyType: 'Apartment',
    listingType: 'rent',
    price: 110000,
    city: 'Mumbai',
    state: 'Maharashtra',
    address: '7 Carter Road, Bandra West',
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    amenities: ['Sea view', 'Parking', 'Lift', '24x7 security'],
    featured: false,
    images: [photo('1600607687939-ce8a6c25118c'), photo('1600566753190-17f0baa2a6c3')],
  },
  {
    agentIndex: 1,
    title: 'Banyan Grove Homes',
    description:
      'An independent 3 BHK house in a gated community with a private garden and a terrace. Close to international schools and the Whitefield tech parks.',
    propertyType: 'House',
    listingType: 'rent',
    price: 65000,
    city: 'Bengaluru',
    state: 'Karnataka',
    address: '31 Banyan Grove Layout, Whitefield',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    amenities: ['Private garden', 'Gated community', 'Terrace', 'Pet friendly'],
    featured: true,
    images: [photo('1568605114967-8130f3a36994'), photo('1586023492125-27b2c045efd7')],
  },
  {
    agentIndex: 1,
    title: 'Koramangala Office Suite',
    description:
      'A ready-to-move office floor with 30 workstations, two meeting rooms and a pantry. Located on a main road with metro access nearby.',
    propertyType: 'Commercial',
    listingType: 'rent',
    price: 240000,
    city: 'Bengaluru',
    state: 'Karnataka',
    address: '4th floor, 80 Feet Road, Koramangala',
    bedrooms: 0,
    bathrooms: 2,
    area: 2400,
    amenities: ['Furnished workstations', 'Meeting rooms', 'Power backup', 'Visitor parking'],
    featured: false,
    images: [photo('1497366216548-37526070297c'), photo('1486406146926-c627a92ad1ab')],
  },
  {
    agentIndex: 1,
    title: 'Lakeview Residence',
    description:
      'A spacious 3 BHK overlooking the lake, with a large balcony and a separate utility area. The tower has a rooftop garden and is close to the Financial District.',
    propertyType: 'Apartment',
    listingType: 'sale',
    price: 14800000,
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'Tower C, Lakeview Enclave, Gachibowli',
    bedrooms: 3,
    bathrooms: 3,
    area: 1680,
    amenities: ['Lake view', 'Rooftop garden', 'Clubhouse', 'Gym', 'Covered parking'],
    featured: true,
    images: [photo('1574362848149-11496d93a7c7'), photo('1554995207-c18c203602cb')],
  },
  {
    agentIndex: 1,
    title: 'Cyber Nest Studio',
    description:
      'A smart studio apartment in Madhapur, a short walk from HITEC City. A good first investment with steady rental demand.',
    propertyType: 'Studio',
    listingType: 'sale',
    price: 4800000,
    city: 'Hyderabad',
    state: 'Telangana',
    address: 'Unit 1108, Cyber Nest, Madhapur',
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    amenities: ['Smart lock', 'Gym', 'Co-working lounge'],
    featured: false,
    images: [photo('1507089947368-19c1da9775ae'), photo('1631049307264-da0ec9d70304')],
  },
  {
    agentIndex: 2,
    title: 'Palm Grove Villa',
    description:
      'A 4 BHK Goan villa surrounded by palms, with a private pool, a sit-out verandah and a staff room. Ten minutes from the beaches of north Goa.',
    propertyType: 'Villa',
    listingType: 'sale',
    price: 42000000,
    city: 'Goa',
    state: 'Goa',
    address: 'Palm Grove Lane, Assagao',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    amenities: ['Private pool', 'Garden', 'Staff room', 'Parking for 3 cars'],
    featured: true,
    images: [photo('1613490493576-7fde63acd811'), photo('1512917774080-9991f1c4c750'), photo('1616594039964-ae9021a400a0')],
  },
  {
    agentIndex: 2,
    title: 'Coconut Lane Plot',
    description:
      'A clear-title residential plot on a quiet lane, suitable for a holiday home. Road access, water and electricity connections available.',
    propertyType: 'Land',
    listingType: 'sale',
    price: 9500000,
    city: 'Goa',
    state: 'Goa',
    address: 'Coconut Lane, Siolim',
    bedrooms: 0,
    bathrooms: 0,
    area: 5400,
    amenities: ['Clear title', 'Road access', 'Water connection'],
    featured: false,
    images: [photo('1500382017468-9049fed747ef')],
  },
  {
    agentIndex: 2,
    title: 'Heritage Courtyard',
    description:
      'A restored 5 BHK haveli-style home built around a central courtyard, with jharokha windows, a rooftop terrace and modern kitchens and bathrooms.',
    propertyType: 'House',
    listingType: 'sale',
    price: 31000000,
    city: 'Jaipur',
    state: 'Rajasthan',
    address: '9 Courtyard Marg, C-Scheme',
    bedrooms: 5,
    bathrooms: 5,
    area: 3800,
    amenities: ['Central courtyard', 'Rooftop terrace', 'Parking', 'Servant quarters'],
    featured: true,
    images: [photo('1580587771525-78b9dba3b914'), photo('1600585154340-be6161a56a0c')],
  },
  {
    agentIndex: 2,
    title: 'Aravali View Villa',
    description:
      'A modern 4 BHK villa with views of the Aravali hills, a landscaped lawn and a home office. Part of a low-density gated community.',
    propertyType: 'Villa',
    listingType: 'sale',
    price: 22500000,
    city: 'Jaipur',
    state: 'Rajasthan',
    address: '18 Aravali Enclave, Jagatpura',
    bedrooms: 4,
    bathrooms: 4,
    area: 2900,
    amenities: ['Lawn', 'Home office', 'Gated community', 'Solar panels'],
    featured: false,
    images: [photo('1600596542815-ffad4c1539a9'), photo('1564013799919-ab600027ffc6')],
  },
];

// buyerIndex points into demoBuyers, propertyIndex into properties.
const reviews = [
  { buyerIndex: 0, propertyIndex: 0, rating: 5, comment: 'The visit was well organised and the flat matched the photos exactly.' },
  { buyerIndex: 1, propertyIndex: 0, rating: 4, comment: 'Great society amenities. Traffic on the main road can be heavy at peak hours.' },
  { buyerIndex: 0, propertyIndex: 8, rating: 5, comment: 'Beautiful villa and a very responsive agent.' },
  { buyerIndex: 1, propertyIndex: 4, rating: 4, comment: 'Lovely garden and a quiet neighbourhood.' },
  { buyerIndex: 0, propertyIndex: 10, rating: 5, comment: 'The courtyard is stunning. Restoration work is high quality.' },
];

module.exports = { demoAgents, demoBuyers, properties, reviews };
